### ISSUE TITLE
Task: Combine V1 and V2 Slack apps

### ISSUE THREAD

**Issue by non-binary** [bitrise-io/bb#2]
### Description: 

The Slack integration overhaul has been pushed to a future release. We are going to combine the V1 and V2 Slack apps and re-deploy it to the new Heroku environment.

#### Subtasks

- [x] Remove credentials from V1 application.
- [x] Upload V1 application to GitHub => #3.
- [x] Adopt command logic in favour of parameter logic => #4.
- [x] Write "coming soon" messages for unimplemented features => #5.
- [x] Deploy to Heroku.
- [x] Request Simon to delete the old deployment.

### Implemented in: 

Rust in the Slack app.
